defaults: &defaults
  GRAB_TIME_LIMIT: 3
  GRAB_DISTANCE: 5000
  GRAB_RECOVER_TIME: 3600
  GRAB_PROBABILITY: 50

development:
  <<: *defaults
  GRAB_TIME_LIMIT: 3
  GRAB_DISTANCE: 150000
  GRAB_RECOVER_TIME: 10
  GRAB_PROBABILITY: 50

product:
  <<: *defaults
